### ISSUE TITLE
Fix use of distances in all algorithms

### ISSUE THREAD

**Issue by mpadge** [mpadge/spatialcluster#27]
Current code mixes both spatial and data-based distance metrics. The algorithms actually require all initial processing steps to be conducted with the *spatial* distances only, and then the tree partitioning to use the data-based distances. That's the reason for current messes like https://github.com/mpadge/spatialcluster/issues/26#issuecomment-1307523058

**Comment by mpadge** [comment]
@geniusadventurer fixing this issue should also yield sensible results with your data. I'll post an updated plot output of your results here.

**Comment by mpadge** [comment]
This looks much better:
![](https://i.imgur.com/9Mr4tFC.png)

**Comment by geniusadventurer** [comment]
Yes. It looks very good.
